##
## Functions makeCacheMatrix() and cacheSolve() work in conjunction to
## invert a matrix and cache the matrix and its inverse. This allows the
## inverse to be subsequently fetched from cache rather than being re-computed.
##
## makeCacheMatrix():
## Enables the creation of an object that effectively caches (encapsulates) a
## matrix and the inverse of that matrix.
## Uses lexical scoping as means for achieving similar effect as object-oriented
## data encapsulation: makeCacheMatrix() analogous to constructor, returns list
## of setter and getter functions for accessing cached matrices.
##
## cacheSolve():
## Computes, or fetches cached value for, the inverse of a square, invertible
## matrix. Works in conjunction with function makeCacheMatrix() to
## accomplish caching of given matrix and its inverse.
##
## Usage example:
##    x <- matrix(data = c(1, 4, 3, 1, 5, 9, 3, 5, 6), nrow = 3, ncol = 3)
##    cm <- makeCacheMatrix(x)
##    myInverse <- cacheSolve(cm)
##

##
## Function makeCacheMatrix uses lexical scoping to effectively cache
## user-specified matrix and its inverse.
## Parameter: mat should be passed as square, invertible matrix object.
##            Defaults to 1x1 with NA value.
## Returns: Named list containing functions for setting and getting matrix
##          and inverse matrix
##
makeCacheMatrix <- function(mat = matrix())
{
    matInv <- NULL ## Stores inverse of mat in this environment; initially NULL
    
    ## Nested function, plays setter role, allowing re-setting mat in env
    ## of makeCacheMatrix function:
    setMat_nst <- function(newMat = matrix())
    {
        mat <<- newMat     ## Reset variable mat in containing environment
        matInv <<- NULL    ## Reset variable matInv in containing env to NULL
    }
    
    ## Nested function, plays getter role that fetches matrix cached in
    ## containing environment:
    getMat_nst <- function() { mat }
    
    ## Nested function. Plays setter role, allowing inverse to be cached in
    ## containing environment:
    setInverse_nst <- function(invrs) { matInv <<- invrs }
    
    ## Nested function. Plays getter role that fetches inverse cached in
    ## containing environment:
    getInverse_nst <- function() { matInv }
    
    ## Return list of named setter/getter functions:
    list(setMat = setMat_nst,
         getMat = getMat_nst,
         setInverse = setInverse_nst,
         getInverse = getInverse_nst)
} ## End top-level function "makeCacheMatrix()"

##
## Function cacheSolve() computes, or fetches cached value for, the inverse
## of a matrix.
## Matrix to be inverted is encapsulated within scope of specified parameter.
## Parameters: cacheMatrix is list of accessor functions, as generated by
##             makeCacheMatrix().
##             ... Optional args that get passed to matrix solver, solve(),
##             such as "tol = <val>" for setting tolerance for detection of
##             singular matrix.
## Returns: Inverse of the cached matrix.
##
cacheSolve <- function(cacheMatrix, ...)
{
    invrs <- cacheMatrix$getInverse()  ## Fetch cached inverse, if any
    if(!is.null(invrs))  ## Check if there was a cached inverse
    {
        ## Found a non-NULL cached inverse...
        message("fetching cached inverse")  ## Informational message to console
        return(invrs)  ## Return inverse immediately
    }
    invrs <- solve(cacheMatrix$getMat(), ...) ## No cached val found; compute it
    cacheMatrix$setInverse(invrs)             ## Cache it
    invrs                                     ## Return inverse matrix
} ## End top-level function "cacheSolve()"
